### ISSUE TITLE
Metronome on Stolen

### ISSUE THREAD

**Issue by BirchBirchBirch** [xrrhythmsuk/xruk-player#41]
Once again, Stolen being double-time nationally causes us grief 😭

The click currently goes at normal speed, which means it's half the rate it should be. I agree with your point previously that having hacks for one song isn't good practice, but might having one for "is this song double-time" might work? (Or even doing something with the "time" parameter, but that sounds like a lot more bother than it's worth.)

Not that we'll ever have another one this annoying if I have anything to do with it...

**Comment by timrog** [comment]
I'm a bit confused about all of this. 

It's 100 bpm @ double time. In notation, presumably it would be cut time so a half note would equal 100bpm. I would expect the metronome to tick therefore at 100/min (i.e at every half note). But you seem to be expect it to click at every quarter note i.e. 200/min

But if we want _everything_ to just double in speed, why don't we just spread out the notes and double the tempo? Yes it would be a crazy bpm, but it would be what we want to achieve. And it would be a quick solution. 

That said, I don't think that _is_ what we want because I wouldn't want to be that time signaller on a march flapping my arm at 200bpm. I'd want to do it at 100 and I'd expect the beat and therefore the metronome to match that.

Further down the line, there's probably a better solution where we have more granular settings for something like
- Divisions per beat
- Beats per bar
- Bars in a pattern
but that's a big change, and I'd still argue that the click track should be on the beat, not necessarily on the quarter note.

**Comment by BirchBirchBirch** [comment]
I do see what you're saying. I think the simplest answer is that _I_ feel it as cut time because that's a tradition I know, but our bands don't work from classical Western notation so it really is effectively a tune at 200bpm, hence the faster whistle in. Presumably people went off the snare part and felt it as the 2 and 4. (I've stood at the back and ticked Stolen, and mostly ended up doing much smaller swishes than normal.)

Honestly, I think recoding Stolen as a tune at 200bpm with two sub-beats would make a lot of sense, especially as we don't really combine tunes on the site. (There were times I was putting demos for all of an instrument's parts together in one file so you couldn't change tempo, but that's an edge case and we've got this site now, anyway.)

I'll do a proposal as a pull request and see what we think.
